version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ffmpeg-network

  ffmpeg:
      image: ghcr.io/scalable-23t1-p2-toktik/ffmpeg-worker/scalable-p2-ffmpeg-worker:latest
      networks:
       - ffmpeg-network
      env_file:
        - .env
      depends_on:
       - redis
  
networks:
  ffmpeg-network:
