on:
    push:
        branches: [ main ]
env:
    REGISTRY: ghcr.io
    BASE_IMG_NAME: ${{ github.repository }}
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
        -   name: Check out the repo
            uses: actions/checkout@v3
        -   name: Log in to the container registry
            uses: docker/login-action@v2
            with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.PASSWORD }}
        -   name: Convert username to lowercase
            id: lowercase_username
            run: echo "::set-env name=BASE_IMG_NAME::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
            env:
                ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        -   name: Derive short SHA name
            id: vars
            run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        -   name: Build the Docker image
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            run: |
                docker build . --file Dockerfile \
                --tag ghcr.io/${{ env.BASE_IMG_NAME }}/scalable-p2-ffmpeg-worker:${{ steps.vars.outputs.sha_short }} \
                --tag ghcr.io/${{ env.BASE_IMG_NAME }}/scalable-p2-ffmpeg-worker:latest
        -   name: Publish the images
            run: |
                docker push ghcr.io/${{ env.BASE_IMG_NAME }}/scalable-p2-ffmpeg-worker:${{ steps.vars.outputs.sha_short }}
                docker push ghcr.io/${{ env.BASE_IMG_NAME }}/scalable-p2-ffmpeg-worker:latest